version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    tty: true
    restart: unless-stopped
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
volumes:
  n8n_data:
